[[Admin]]
== 회원

=== 모든 회원 조회 : 기간 조건

operation::admin/members/get-members[snippets='http-request,http-response']

=== 회원 이름 수정

operation::admin/members/update-member-name[snippets='http-request,http-response']



== 쿠폰

=== 쿠폰 조회 : 기간 조건 + 모든 상태(all)

operation::admin/coupons/get-coupons-all[snippets='http-request,http-response']

=== 쿠폰 조회  : 기간 + 상태 조건
(not_used / reserving / reserved / used / expired)

operation::admin/coupons/get-coupons-status[snippets='http-request,http-response']

=== 쿠폰 만료

operation::admin/coupons/expire[snippets='http-request,http-response']

== 쿠폰 시리얼

=== 쿠폰 시리얼 생성
operation::admin/serial/save-serial[snippets='http-request,http-response']

=== 쿠폰 시리얼 조회
operation::admin/serial/get-serial[snippets='http-request,http-response']

=== 시리얼 번호로 QR 링크 생성
operation::admin/serial/get-link[snippets='http-request,http-response']

== 어드민 로그인
operation::admin/authentication/sign-in[snippets='http-request,http-response']

== 조직

=== 조직 생성
operation::admin/organization/create-organization[snippets='http-request,http-response']

=== 조직 검색
operation::admin/organization/get-organizations[snippets='http-request,http-response']
