export const BASE_URL = `${process.env.API_URL}`;

export const API_PATH = {
  RECEIVED_COUPONS_ALL: `/coupons/received?status=all`,
  RECEIVED_COUPONS_NOT_USED: `/coupons/received?status=not-used`,
  RECEIVED_COUPONS_USED: `/coupons/received?status=used`,
  SENT_COUPONS: `/coupons/sent`,
  SEND_COUPON: `/coupons/send`,
  MEMBERS: `/members`,
  PROFILE: `/members/me`,
  PROFILE_NAME: `/members/me/name`,
  PROFILE_IMAGE: `/members/me/profile-image`,
  RESERVATIONS: `/reservations`,
  RESERVATIONS_SENT: `/reservations/sent`,
  RESERVATIONS_RECEIVED: `/reservations/received`,
  SIGN_IN: userCode => `/sign-in?code=${userCode}`,
  SIGN_UP: '/sign-up',
  COUPON_DETAIL: '/coupons',
  GET_COUPON_DETAIL: couponId => `/coupons/${couponId}`,
  MEETINGS: '/meetings',
  CANCEL_RESERVATION: reservationId => `/reservations/${reservationId}/cancel`,
  COMPLETE_MEETING: meetingId => `/meetings/${meetingId}`,
  GET_COUPONS_EXCHANGE_COUNT: `/coupons/count`,
  GET_USER_HEARTS: `/hearts/me`,
  POST_USER_HEART: `/hearts/send`,
  GET_QR_COUPON: code => `/coupon-serials?code=${code}`,
  POST_QR_SERIAL: '/coupon-serials',
  COMPLETE_COUPON: couponId => `/coupons/${couponId}/use`,
  ORGANIZATIONS: '/organizations/me',
  JOIN_ORGANIZATION: '/organizations/join',
  UPDATE_LAST_ACCESSED_ORGANIZATION: id => `/organizations/${id}/access`,
};
