export const ROUTE_PATH = {
  ON_SUCCESS: '/success',
  ON_FAILURE: '/failure',
  NOT_FOUND: '*',
  EXACT_MAIN: '/',
  SELECT_RECEIVER: '/select-receiver',
  ENTER_COUPON_CONTENT: '/enter-coupon-content',
  SIGN_IN: '/sign-in',
  REQUESTED_COUPONS: '/requested-coupons',
  PROFILE: '/profile',
  CREATE_RESERVATION: '/create-reservation',
  RESERVATIONS: '/reservations',
  ENTER_NICKNAME: '/enter-nickname',
  MEETINGS: '/meetings',
  HEARTS: '/hearts',
  JOIN_ORGANIZATION: '/join-organization',
};
