server:
  port: 8180
  tomcat:
    max-connections: 100
    threads:
      max: 50

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:thankoo-test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      maximumPoolSize: 51
      idleTimeout: 10000

security:
  jwt:
    token:
      secret-key: dasdc338hfhghsn21sdf1jvnu4ascasv21908fyhas2a
      expire-length: 1000000

oauth:
  google:
    client-id: client-id
    client-secret: client-secret
    grant-type: authorization_code
    redirect-uri: /callback
    token-url: http://localhost:8180/oauth/token

slack:
  authorization: Bearer xoxb-39499534989-12389491129-12359892049
  users-uri: http://localhost:8180/users/list
  message-uri: http://localhost:8180/chat/postMessage

profile-image:
  image-url-path: /profile-image/
  image-path: classpath:static/profile-image/*.svg

origin: https://thankoo.co.kr

admin:
  encryption:
    pbkdf2:
      salt: csclxnexia70000000
      iteration-count: 65536
      key-length: 128
  token:
    key: acwoFWrRtHoTpxczELrTOhfsQNewXLhviNzE
    validity: 1000000
