name: Backend CI

on:
  push:
    branches:
      - main
      - develop
      
  pull_request:
    branches: 
      - main
      - develop
      
    paths: ["backend/**"]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend
   
    steps:
      - name: action checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
