name: FrontEnd CI

on:
  push:
    branches: ['**']

  pull_request:
    branches: ['**']
    paths: ['frontend/**']
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: yarn run build
          start: yarn dev
          browser: chrome
